---
# tasks file for docker_install
- name: ensure docker is installed
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Install Docker Module for Python
  pip: name=docker
