---
# tasks file for docker_install
- name: ensure docker is installed
  apt:
    name:
      - python3-pip
      - docker
      - docker-compose
    state: present

- name: Install Docker Module for Python
  pip3: name=docker
