---
# tasks file for prod
- name: Download and install tomcat container
  docker_compose:
    image: tomcat:9.0.19-jre8-alpine
    volumes:
      - "/tmp/shared_folder:/usr/local/tomcat/webapps"
    ports: 
      - "8080:8080"

- name: sync war
  synchronize:
    mode: push
    src: '{{ src_path }}'
    dest: '{{ dest_path }}'
  delegate_to: '{{ build_server }}'