---
# tasks file for prod
- name: Download and install tomcat container
  docker_compose:
    project_name: tomcat
    definition:
      version: '2'
      services:
        tomcat:
          image: tomcat:9.0.19-jre8-alpine
          volumes:
            - /shared_folder:/usr/local/tomcat/webapps:rw
          ports: 
            - "8080:8080"

- name: sync war
  synchronize:
    mode: push
    src: '{{ src_path }}/hello-1.0.war'
    dest: '{{ dest_path }}'
  delegate_to: '{{ build_server }}'